source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.2'

# Use sqlite3 as the database for Active Record
gem 'mysql2'
gem 'sqlite3'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jquery-ui-sass-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

gem 'libv8'
gem 'carrierwave'
gem "fog"
gem 'uuidtools'
gem 'delayed_job_active_record'
gem 'daemons'
gem 'exception_notification'
gem 'therubyracer'
gem 'json'
gem 'newrelic_rpm'
gem 'mini_magick'
gem "bcrypt-ruby"
gem "useragent"
gem 'rubyzip'
gem 'nokogiri'
gem 'quiet_assets', :group => :development
gem 'rails-i18n'
gem 'htmlentities'
gem "font-awesome-rails"
gem 'omniauth'
gem 'omniauth-twitter'
gem 'omniauth-facebook'
gem 'twitter'
gem 'koala'
gem 'curb'
gem 'twilio-ruby'
gem 'pdf-reader'
gem 'twocheckout'
gem "pandoc-ruby", "~> 0.6.1"
gem 'feedzirra',"~> 0.2.0.rc2"
gem 'capistrano',  '~> 2.15'
gem 'angularjs-rails'
gem 'angular_rails_csrf'

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
